Support for IIIF Image API & Presentation API manifests
vitrivr/cineast pull request #217
Opened 2021-07-21 10:15 UTC by singaltanmay

This PR includes all the changes mentioned in #211. Additionally this PR adds support for downloading all images contained in a Presentation API manifest.json through the manifestUrl mentioned in the extraction job file.

2021-07-23 14:26 UTC, silvanheller commented
> This PR includes all the changes mentioned in #211.
Does that mean we can close #211?

2021-07-23 17:10 UTC, singaltanmay commented
> > This PR includes all the changes mentioned in #211.
> 
> Does that mean we can close #211?

Yes, #211 is now obsolete. You can close it if you want.

2021-08-11 07:46 UTC, Spiess requested changes
The changes have passed all checks, I don't see any issues with the code and I have tested the new functionality myself.

As soon as the remaining unnecessary "author", "version" and "created" tags have been removed from doc-strings, the changes can be merged.

2021-08-17 09:29 UTC, Spiess approved these changes

2021-08-17 11:59 UTC, lucaro approved these changes

2021-08-17 15:29 UTC, merged