Allow specification of metadata to be fetched for Websocket Queries
vitrivr/cineast pull request #234
Opened 2021-11-18 18:27 UTC by silvanheller

Introduces the `MetadataAccessSpecification`, of which a list can be handed to Cineast. `*` for either domain or keys mean all elements should be fetched. For backwards-compatibility, `null` is treated as `*`, `*`, which means all metadata is fetched.

Implementation is unit-tested.

Closes #166 

As a simple comparison, on the LSC 21 dataset, this reduces metadata fetch time for a tag query `sushi_bar` (5k results) from approx. 2.5 to 2 seconds:

(old)
```
[11-18 19:19:04.449][DEBUG][metadata-load-write-1db170ea-e7db-4117-b49c-d1bd4afc0a4a] AbstractMetadataReader - Performed metadata lookup for 6671 ids in 2439 ms. 92879 results.
[11-18 19:19:04.514][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 44 ms
[11-18 19:19:04.656][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId0: Successfully wrote message QR_METADATA_S in 187 ms
```
(new)
```
[11-18 19:15:10.310][DEBUG][metadata-load-write-c6917953-51e3-400b-b06a-ea492ce166ba] AbstractMetadataReader - Performed metadata lookup for 6671 ids in 1970 ms. 39914 results.
[11-18 19:15:10.372][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 44 ms
[11-18 19:15:10.435][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId0: Successfully wrote message QR_METADATA_S in 108 ms
```

For larger result-sets (i.e. hitting the config limit, currently 20k) it goes from 9.4 to 6 seconds + there are (obviously) gains in serialization speed.

(old)
```
[11-18 19:20:46.498][DEBUG][metadata-load-write-5066239b-fbe4-4bcb-9af6-033e51b4249c] AbstractMetadataReader - Performed metadata lookup for 20000 ids in 9473 ms. 315522 results.
[11-18 19:20:46.600][TRACE][metadata-ws-write-queryId3] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 8 ms
[11-18 19:20:46.620][TRACE][metadata-ws-write-queryId3] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId3: Successfully wrote message QR_METADATA_S in 28 ms
[11-18 19:20:46.664][TRACE][metadata-ws-write-queryId2] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 72 ms
[11-18 19:20:46.664][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 72 ms
[11-18 19:20:46.823][TRACE][metadata-ws-write-queryId1] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 231 ms
[11-18 19:20:46.935][TRACE][metadata-ws-write-queryId2] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId2: Successfully wrote message QR_METADATA_S in 343 ms
[11-18 19:20:47.054][TRACE][metadata-ws-write-queryId2] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId0: Successfully wrote message QR_METADATA_S in 463 ms
[11-18 19:20:47.170][TRACE][metadata-ws-write-queryId2] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId1: Successfully wrote message QR_METADATA_S in 578 ms
```

(new)
```
[11-18 19:23:36.383][DEBUG][metadata-load-write-6437f6c0-f2bc-4f2f-8653-45a3615d17ab] AbstractMetadataReader - Performed metadata lookup for 20000 ids in 6278 ms. 134793 results.
[11-18 19:23:36.486][TRACE][metadata-ws-write-queryId1] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 50 ms
[11-18 19:23:36.534][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler - Serialization for QR_METADATA_S in 98 ms
[11-18 19:23:36.541][TRACE][metadata-ws-write-queryId1] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId1: Successfully wrote message QR_METADATA_S in 105 ms
[11-18 19:23:36.674][TRACE][metadata-ws-write-queryId0] AbstractWebsocketMessageHandler$1 - metadata-ws-write-queryId0: Successfully wrote message QR_METADATA_S in 238 ms
```

2021-11-18 22:48 UTC, sauterl requested changes

2021-11-18 22:48 UTC, sauterl commented on cineast-core/src/main/java/org/vitrivr/cineast/core/util/CineastConstants.java
> +  public static final String DOMAIN_COL_NAME = "domain";
I don't fully understand why `OBJECT_ID_COLUMN_QUALIFIER` and `DOMAIN_COL_NAME` coexist in this constants collection. I'd suggest to use either _qualifier_ or _name_ :-D

2021-11-18 22:48 UTC, sauterl commented
Generally speaking I like this PR very much, there are a few minor engineering points I think are to be improved.

2021-11-29 15:32 UTC, silvanheller commented on cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/TemporalQuery.java
> +  private final List<MetadataAccessSpecification> metadataSpec;
I think the entire API uses Lists

2021-12-03 08:16 UTC, sauterl approved these changes
Looks good to me. Thanks @silvanheller for the PR

2021-12-03 08:22 UTC, merged