Making decorator for text retrieval configurable
vitrivr/cineast pull request #324
Opened 2022-07-25 17:59 UTC by silvanheller

Some time ago, each term used to be decorated with `~` at the end for fuzzy matches. This got lost at some point, which leads to a query for `JAMES` to not match `AMES` in an OCR database. To fix this, this PR adds configurable decorators for all text-retrieval classes. Default behavior stays the same.

Additionally, it adds the option to configure entity-names for text retrieval classes and fixes rare edge-cases where batch-import would cause problems.

2022-07-25 19:32 UTC, lucaro requested changes

2022-07-25 19:32 UTC, lucaro commented on cineast-core/src/main/java/org/vitrivr/cineast/core/features/ProvidedOcrSearch.java
> +  public ProvidedOcrSearch(LinkedHashMap<String, String> properties) {
Why specifically does this need to be a `LinkedHashMap` and not just a `Map`?

2022-07-25 19:32 UTC, lucaro commented on cineast-core/src/main/java/org/vitrivr/cineast/core/features/abstracts/AbstractTextRetriever.java
> +  public AbstractTextRetriever(String defaultTableName, LinkedHashMap<String, String> properties) {
Again, why so specific?

2022-07-25 20:07 UTC, silvanheller commented
I've made changes to all features which were using a specific type of map in their constructor and did not need it.

2022-07-26 07:45 UTC, lucaro approved these changes

2022-07-26 07:53 UTC, merged