Make log level configurable (#377)
vitrivr/cineast pull request #378
Opened 2023-05-10 13:37 UTC by x4e-jonas

Uses `LOG_LEVEL` to configure log level. Default changed to `INFO`.

2023-05-11 13:50 UTC, silvanheller approved these changes

2023-05-11 13:50 UTC, silvanheller approved these changes

2023-05-11 14:35 UTC, lucaro requested changes
The way this is implemented only makes sense under the assumption that cineast is the only application running in a particular environment, such as a docker container. In all other cases, it uses a generic environment variable without any context. To make this more generally applicable, I'd suggest calling the variable something like `CINEAST_LOG_LEVEL`, in case there are several applications in the same environment that use a similar mechanism.

2023-07-18 07:38 UTC, lucaro approved these changes
Looks reasonable to me

2023-07-19 06:28 UTC, merged